version: "3.9"

services:
  main_node:
    build:
      context: .
    container_name: main_node
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/main_db
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
