version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: fastapi_backend
    ports:
      - "5001:5001" # Обратите внимание на кавычки
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/main_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432" # Аналогично, кавычки обязательны
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "8002:8002"

volumes:
  postgres_data:
